version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
  open-pull-requests-limit: 1
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: weekly
    day: wednesday
    time: "03:00"
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
