version: '3'

services:
  postgresql:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hammoc_prod
    ports:
      - '5432:5432'
