# This file is for running Citus DB instead of PostgreSQL for development.
# Use:
#   docker-compose -f docker-compose.citus.yml
---
version: '2.1'

services:
  # Citus database coordinator, receiving Postgres connections
  #  -> https://hub.docker.com/r/citusdata/citus
  citus_master:
    image: citusdata/citus:8.1.1
    ports:
      - "${MASTER_EXTERNAL_PORT:-5432}:5432"
    labels:
      - 'com.citusdata.role=Master'

  # Citus database worker, operating on the data in Postgres
  citus_worker:
    image: citusdata/citus:8.1.1
    labels:
      - 'com.citusdata.role=Worker'
    depends_on:
      citus_manager:
        condition: service_healthy

  # Python helper container to add workers to the master/coordinator
  #   -> https://hub.docker.com/r/citusdata/membership-manager
  citus_manager:
    image: citusdata/membership-manager:0.2.0
    environment:
      CITUS_HOST: citus_master
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      citus_master:
        condition: service_healthy
