# Alpine Linux image with Erlang, Elixir, Hex and Rebar installed
#   -> https://hub.docker.com/r/bitwalker/alpine-elixir
FROM bitwalker/alpine-elixir:1.8.0

ENV HOME=/opt/app/ TERM=xterm

WORKDIR /opt/app

# Cache elixir deps
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

COPY . .
